### PR TITLE
Update footer

### PR DESCRIPTION
**Pull request by pollygee**

### CODE REVIEW

**Review by meg-gutshall — CHANGES_REQUESTED** [review]
The one thing I don't like about this update is the form change. If you look in the `theme_includes/subscribe` partial, you'll see there's `mailchimp_list` and `mailchimp_input_name` variables defined. These are set in the `config.yml` file but I don't have access to the MailChimp account to get this data. I'd much rather go with using this partial since I already coded out some CSS on the original footer for this form. What do you think?

**Comment by meg-gutshall** [comment]
By the way, the rest of the changes are good! 👍 

I just put some of them into partials and changed that `site.url` variable to `site.baseurl` variable because it's more specific.

**Comment by pollygee** [comment]
@meg-gutshall I think that's all fine.  You can change the form to be whatever you want.  I was just trying to get us some better content in the footer, I don't mind if you change it at all, especially if you've already done some work to make it look good.  That's great.

The one thing I am curious about is why you added back in the social media links for my account.  I don't think it makes sense to have link looking things that don't link anywhere so I took out the links for me that are not relevant, but you added them back in.  I think it looks weird, but if you want to leave them all in there, that's fine.  I'll never link Fb or instagram  or things like that for me.

**Comment by pollygee** [comment]
Something broke the Home links.  I see it links to `{{ site.baseurl }}` but it's taking me to my profile page instead of home?

**Comment by meg-gutshall** [comment]
> Something broke the Home links. I see it links to `{{ site.baseurl }}` but it's taking me to my profile page instead of home?

Ahh... It refreshes the page you're currently viewing. I think those links **have** to use `{{ site.url }}`. Good catch!! 🎉

**Comment by meg-gutshall** [comment]
> @meg-gutshall I think that's all fine. You can change the form to be whatever you want. I was just trying to get us some better content in the footer, I don't mind if you change it at all, especially if you've already done some work to make it look good. That's great.

Sounds good! We spoke about this more over Slack and I think we're on the same page for this MVP release.

> The one thing I am curious about is why you added back in the social media links for my account. I don't think it makes sense to have link looking things that don't link anywhere so I took out the links for me that are not relevant, but you added them back in. I think it looks weird, but if you want to leave them all in there, that's fine. I'll never link Fb or instagram or things like that for me.

I totally get that. Since it's not MVP, I'm not working on it right now, but I'm going to have those icons show conditionally if there is a corresponding link in the bio page front matter. Some other people may change their mind, make a new social account, or get their info to us later so I wanted there to be a way to leave up those input options just in case!

I'm glad you asked about this though! You're definitely picking up detailed things that I may miss. 😄

**Pull request merged**
