### PR TITLE
Fix sponsors slider

### PR DESCRIPTION
**Pull request by pollygee**
Fixing again.

### CODE REVIEW

**Comment by pollygee** [comment]
Home

**Comment by meg-gutshall** [comment]
Hey Polly!

It looks good except that it wasn’t inside the bootstrap container (to keep it consistent with the side margins throughout the site) and when I added it the sponsor images shrunk up like crazy. You’ll see if you pull down that one change I just made.

Also Isabel recommended that we display only four logos at a time. That was totally my bad—I forgot to tell you that. I’m so sorry. :grimacing:

Do you think you could change it to four logos and leave a little less spacing between them?

**Comment by pollygee** [comment]
@meg-gutshall updated!  4 images only, and changed the size!
Home

**Comment by meg-gutshall** [comment]
Looks terrific! ...Except it doesn't move. 🙁

**Comment by meg-gutshall** [comment]
TEAMWORK!! 💯

**Review by meg-gutshall — APPROVED** [review]

**Pull request merged**
